ALTER TABLE "Project"
  ALTER COLUMN "neighborhood" DROP NOT NULL,
  ALTER COLUMN "city" DROP NOT NULL,
  ALTER COLUMN "state" DROP NOT NULL,
  ADD COLUMN "plannedBlocks" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "plannedLots" INTEGER NOT NULL DEFAULT 0;
